package pojo;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope(value = "prototype")
public class DeployMode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPOLYMODE.d_id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPOLYMODE.d_name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPOLYMODE.d_id
     *
     * @return the value of DEPOLYMODE.d_id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPOLYMODE.d_id
     *
     * @param id the value for DEPOLYMODE.d_id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPOLYMODE.d_name
     *
     * @return the value of DEPOLYMODE.d_name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPOLYMODE.d_name
     *
     * @param name the value for DEPOLYMODE.d_name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}