package mapper;

import pojo.DeployMode;

public interface DeployModeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPOLYMODE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPOLYMODE
     *
     * @mbg.generated
     */
    int insert(DeployMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPOLYMODE
     *
     * @mbg.generated
     */
    int insertSelective(DeployMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPOLYMODE
     *
     * @mbg.generated
     */
    DeployMode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPOLYMODE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeployMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPOLYMODE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeployMode record);
}