package mapper;

import pojo.Leave;

public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _LEAVE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _LEAVE
     *
     * @mbg.generated
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _LEAVE
     *
     * @mbg.generated
     */
    int insertSelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _LEAVE
     *
     * @mbg.generated
     */
    Leave selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _LEAVE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _LEAVE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Leave record);
}